title: "Siv3D リファレンス v0.6.6"
summary: "◆ 内容\n2D/3D ゲーム、メディアアート、ビジュアライザ、シミュレータなど、可視化やインタラクションに関わるプログラムを、驚くほど短い、楽しく簡単なコードで書けるモダンな C++ フレームワーク Siv3D のリファレンスです。\n\n◆ 対応バージョン\nOpenSiv3D v0.6.6\nhttps://github.com/Siv3D/OpenSiv3D"
topics: ["cpp", "siv3d", "game", "gamedev", "クリエイティブコーディング"] # トピック（5つまで）
published: true # falseだと下書き
price: 0
chapters:
  - introduction
  - setup
  - hello-siv3d
  - quick-example
  - tutorial-basic
  - tutorial-shape
  - tutorial-animation
  - tutorial-shape-2
  - tutorial-string
  - tutorial-data-structure
  - tutorial-2d-intersection
  - tutorial-texture
  - tutorial-video
  - tutorial-format
  - tutorial-gui
  - tutorial-random
  - tutorial-time
  - tutorial-font
  - tutorial-scene
  - tutorial-keyboard
  - tutorial-mouse
  - tutorial-utility
  - tutorial-audio
  - tutorial-asset
  - tutorial-renderstates2d
  - tutorial-effect
  - tutorial-filesystem
  - tutorial-textfile
  - tutorial-configfile
  - tutorial-binaryfile
  - tutorial-dialog
  - tutorial-dragdrop
  - tutorial-http
  - tutorial-resource
  - tutorial-scene-manager
  - tutorial-gamepad
  - tutorial-image
  - tutorial-rendertexture
  - tutorial-shader2d
  - tutorial-3d
  - tutorial-3d-2
  - tutorial-3d-intersection
  - tutorial-microphone-webcam
  - tutorial-tcp
  - tutorial-release
  - tutorial-next
  - web
  - sample-game
  - sample-application
  - sample-visual
  - sample-algorithm
  - sample-ui
  - sample-image
  - sample-2d-physics
  - sample-device
  - sample-links
  - community
  - support
  - sponsor
  - build
  - guideline
  - productivity
  - course-circles
  - course-tic-tac-toe
  - course-network-visualization
  - course-game-launcher
  - course-quick-turorial
  - troubleshooting-setup
  - troubleshooting-run
  - api-b
  - api-c
  - api-p
  - api-q
  - api-r
  - api-s
  - api-t
  - api-u
  - api-z
